-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 13:27:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Repse` DEFAULT CHARACTER SET utf8 ;
USE `Repse` ;

-- -----------------------------------------------------
-- Table `mydb`.`PagoIMSS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repse`.`PagoIMSS` (
  `Folio SUA` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Periodo` VARCHAR(45) NOT NULL,
  `PP` VARCHAR(45) NULL,
  `LC` VARCHAR(45) NOT NULL,
  `RegistroPatronal` VARCHAR(45) NOT NULL,
  `Importe IMSS` VARCHAR(45) NULL,
  `ImporteRCV` VARCHAR(45) NULL,
  `ImporteVIV` VARCHAR(45) NULL,
  `ImporteACV` VARCHAR(45) NULL,
  `Total a pagar` VARCHAR(45) NOT NULL,
  `Banco` VARCHAR(45) NOT NULL,
  `FechaPago` VARCHAR(45) NOT NULL,
  `Archivo` VARCHAR(45) NOT NULL,
  `FechaProcesamiento` VARCHAR(45) NOT NULL,
  `Remitente` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Folio SUA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeclaracionIMSS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repse`.`DeclaracionIMSS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `LC` VARCHAR(45) NULL,
  `FechaPago` VARCHAR(45) NULL,
  `PeriodoPago` VARCHAR(45) NOT NULL,
  `RazonSocial` VARCHAR(45) NOT NULL,
  `RegistroPatronal` VARCHAR(45) NOT NULL,
  `RFC` VARCHAR(45) NOT NULL,
  `ImporteIMSS` VARCHAR(45) NULL,
  `Total` VARCHAR(45) NOT NULL,
  `Archivo` VARCHAR(45) NOT NULL,
  `FechaProcesamiento` VARCHAR(45) NOT NULL,
  `Remitente` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PagoISR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repse`.`PagoISR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NombreDocumento` VARCHAR(45) NOT NULL,
  `LineaCaptura` VARCHAR(45) NOT NULL,
  `FechaPago` VARCHAR(45) NOT NULL,
  `TotalAPagar` VARCHAR(45) NOT NULL,
  `Banco` VARCHAR(45) NOT NULL,
  `NombreSolicitante` VARCHAR(45) NOT NULL,
  `NombreArchivo` VARCHAR(45) NOT NULL,
  `FechaProcesamiento` VARCHAR(45) NOT NULL,
  `Remitente` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeclaracionISR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repse`.`DeclaracionISR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RFC` VARCHAR(45) NOT NULL,
  `RS` VARCHAR(45) NOT NULL,
  `Ejercicio` VARCHAR(45) NOT NULL,
  `Periodo` VARCHAR(45) NOT NULL,
  `ConceptoIVA` VARCHAR(45) NULL,
  `IVA` VARCHAR(45) NULL,
  `NombreArchivo` VARCHAR(45) NOT NULL,
  `Administracion` VARCHAR(45) NOT NULL,
  `ACargoISR` VARCHAR(45) NOT NULL,
  `ObvservacionISRSyS` VARCHAR(45) NOT NULL,
  `NombreDocumento` VARCHAR(45) NOT NULL,
  `LineaCaptura` VARCHAR(45) NOT NULL,
  `TotalPagado` VARCHAR(45) NULL,
  `TipoDeclaracion` VARCHAR(45) NOT NULL,
  `NumOperacion` VARCHAR(45) NOT NULL,
  `FechaProcesamiento` VARCHAR(45) NOT NULL,
  `Remitente` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
